//Create all the constants to be used in Redux
export const CREATE_TWEET = "CREATE_TWEET";
export const LIKE_TWEET = "LIKE_TWEET";
export const RETWEET_TWEET = "RETWEET_TWEET";
export const REPLY_TWEET = "REPLY_TWEET";
export const BOOKMARK_TWEET = "BOOKMARK_TWEET";
export const DELETE_TWEET = "DELETE_TWEET";
export const GET_BOOKMARKED_TWEETS = "GET_BOOKMARKED_TWEET";
export const GET_LIKED_TWEETS = "GET_LIKED_TWEETS";
export const SIGN_UP = "SIGN_UP";
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_ERROR = "SIGN_IN_ERROR";
export const FETCH_LOGIN = "FETCH_LOGIN";//sample constant
export const GET_TOP_TEN_TWEETS_BY_VIEWS = "GET_TOP_TEN_TWEETS_BY_VIEWS";
export const GET_TOP_TEN_TWEETS_BY_LIKES = "GET_TOP_TEN_TWEETS_BY_LIKES";
export const GET_TOP_TEN_TWEETS_BY_RETWEETS = "GET_TOP_TEN_TWEETS_BY_RETWEETS";
export const GET_NUMBER_OF_HOURLY_TWEETS = "GET_NUMBER_OF_HOURLY_TWEETS";
export const GET_NUMBER_OF_DAILY_TWEETS = "GET_NUMBER_OF_DAILY_TWEETS";
export const GET_NUMBER_OF_MONTHLY_TWEETS = "GET_NUMBER_OF_MONTHLY_TWEETS";
export const GET_PROFILE_VIEW_DATA = "GET_PROFILE_VIEW_DATA";
export const CREATE_LIST = "CREATE_LIST";
export const ADD_MEMBER = "ADD_MEMBER";
export const REMOVE_MEMBER = "REMOVE_MEMBER";
export const GET_LIST_ID = "GET_LIST_ID";
export const GET_TWEETS_BY_LIST = "GET_TWEETS_BY_LIST";
export const GET_MEMBERS_IN_LIST = "GET_MEMBERS_IN_LIST";
export const GET_SUBSCRIBERS_IN_LIST = "GET_SUBSCRIBERS_IN_LIST";
export const GET_MEMBERLISTS = "GET_MEMBERLISTS";
export const GET_SUBSCRIBEDLIST = "GET_SUBSCRIBEDLIST";
export const GET_OWNEDLISTS = "GET_OWNEDLISTS";
export const GET_TWEETS_LIST = "GET_TWEETS_LIST";
export const GET_PROFILE = "GET_PROFILE";
export const GET_USER_TWEETS = "GET_USER_TWEETS";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWEES = "GET_FOLLOWEES";


